---
title: "Wrangling Worldwide Covid Data"
author: "Emma Strawbridge"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lubridate)
library(tidyverse)
library(dplyr)
library(readxl)
library(ggrepel)
library(broom)
library(GGally)

#data can be downloaded at:
#https://github.com/owid/covid-19-data/tree/master/public/data for bigBoy
#https://data.oecd.org/inequality/poverty-rate.htm#indicator-chart for poverT -- unused but explored

bigBoy <- read_excel("~/Desktop/RStudio231/2-strawbridge-emma/blog2-SunnyDay/emma/data/oc.xlsx")
poverT <- read.csv("~/Desktop/RStudio231/2-strawbridge-emma/blog2-SunnyDay/emma/data/pc.csv")

```

```{r poverT sort}
#goal of this section is to only get: total poverty and whatever else i don't need OUT
pTprep <- poverT %>%
  filter(SUBJECT == "TOT",
         TIME == 2020) %>%
  select(LOCATION, Value, TIME) %>%
  rename(country = LOCATION,
         poverty_rate = Value)
#okay so can't really use poverty here because it's sooooooo incomplete. but the thought was there I guess
```

```{r big boy sort}
#oh brother
#goal of this section is remove useless variables
bigprep <- bigBoy %>%
  rename(country = iso_code) %>%
  mutate(date = ymd(date)) %>%
  select(-new_cases_smoothed, -new_cases_smoothed_per_million, -new_deaths_smoothed, -new_deaths_smoothed_per_million, -new_tests_smoothed, -new_tests_smoothed_per_thousand, -new_vaccinations_smoothed, -new_vaccinations_smoothed_per_million, -new_people_vaccinated_smoothed, -new_people_vaccinated_smoothed_per_hundred) 
#still totally a ton of data but whatever let's just combine
```

```{r}
#Hm okay let me try this a better way
bigprep2 <- bigprep %>%
  select(country, continent, location, date, population_density, gdp_per_capita, hospital_beds_per_thousand, cardiovasc_death_rate, diabetes_prevalence, handwashing_facilities, people_vaccinated_per_hundred, new_deaths_per_million) %>%
  filter(date > '2020-03-10')

DSMarch <- bigprep2 %>%
  filter(date == '2020-03-11')

DSTimePrep <- bigprep2 %>%
  filter(date > '2021-01-01') %>%
  group_by(country) %>%
  arrange(date) %>%
  filter(new_deaths_per_million <= 1)

t.first <- DSTimePrep[match(unique(DSTimePrep$country), DSTimePrep$country),]

#OKAY! there is something HERE!!!!

GettingThere <- t.first %>% # left in world data just in case
  filter(country != "OWID_OCE", country != "OWID_LMC", country != "OWID_LIC"
         , country != "OWID_KOS", country != "OWID_ASI", country != "OWID_AFR"
         , country != "OWID_NAM", country != "OWID_HIC", country != "OWID_EUN"
         , country != "OWID_EUR", country != "OWID_SAM", country != "OWID_UMC") %>%
  mutate(daysuntildrop = date) %>%
  select(country, daysuntildrop)

#Daystil metric
biggie <- left_join(GettingThere, DSMarch, by= "country") %>%
  mutate(daystil = as.numeric(difftime(as.Date(daysuntildrop), as.Date(date), units = c("days"))))

write.csv(biggie, file = "data/biggie.csv")

```

